import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

// The generated AppLocalizations class lives in l10n/generated/
// and is generated by running `flutter gen-l10n`.
// Re-export so callers can import this single file.
export 'package:schlicht/l10n/generated/app_localizations.dart';

import '../../l10n/generated/app_localizations.dart';

/// Supported locales and delegates for Schlicht.
/// Renamed from AppLocalizations to avoid colliding with the generated class.
abstract class AppLocalizationsWrapper {
  static const List<Locale> supportedLocales = [
    Locale('de'),
    Locale('en'),
  ];

  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates = [
    AppLocalizations.delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];
}
